# Required
version: 2

tools:
  os: ubuntu-20.04  # <- add this line
    python: "3.9"
    r: "4.1"

mkdocs:
  configuration: docs/mkdocs.yml

# Optionally declare the Python requirements required to build your docs
python:
   install:
   - requirements: requirements.txt