site_name: ssPA Docs

theme:
  name: "material"
  palette:
    primary: deep purple
    accent: deep purple

docs_dir: 'docs'
site_dir: 'site'


plugins:
  - search:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: false
          options:
            docstring_style: google
            docstring_options:
              ignore_init_summary: no
            merge_init_into_class: no
            show_submodules: yes

nav:
  - Home: index.md
  - Tutorials: tutorials.md
  - Reference:
    - gendocs_docs/reference/identifier_conversion.md
    - gendocs_docs/reference/download_pathways.md
    - gendocs_docs/reference/load_pathways.md
    - gendocs_docs/reference/utils.md
    - Pathway analysis:
      - gendocs_docs/reference/ORA.md
      - gendocs_docs/reference/GSEA.md
      - Single sample methods:
        - gendocs_docs/reference/SVD.md
        - gendocs_docs/reference/kPCA.md
        - gendocs_docs/reference/ssClustPA.md
        - gendocs_docs/reference/GSVA.md
        - gendocs_docs/reference/ssGSEA.md
        - gendocs_docs/reference/zscore.md
  
