name: sspa-docs
on:
  push:
    branches:
      - master 
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material 
      - run: pip install mkdocstrings-python
      - run: pip install pymdown-extensions
      - run: pip install mkgendocs
      - name: generate docs
        run: gendocs --config mkgendocs.yml
      - name: Deploy docs
        working-directory: ./docs
        run: mkdocs build
        run: mkdocs gh-deploy --force
